services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - fireants_network

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    networks:
      - fireants_network
    depends_on:
      - app

networks:
  fireants_network:
